### ISSUE TITLE
[ISSUE] Could not find any versions of go

### ISSUE THREAD

**Issue by vzool** [dotboris/alt#93]
Hi, I would like to use your command to switch between **golang** versions, but the `alt` command compliant with the following:

```shell
➜  ~ alt scan go
Sorry, could not find any versions of go
```
So, here are some outputs to show you my current situation of my workstation:

```shell
➜  ~ go version
go version go1.11.13 linux/amd64
➜  ~ which go
/usr/bin/go
➜  ~ ll /usr/bin/go
lrwxrwxrwx 1 root root 20 Aug 15 15:00 /usr/bin/go -> /etc/alternatives/go
➜  ~ ll /etc/alternatives/go
lrwxrwxrwx 1 root root 25 Apr  1  2019 /etc/alternatives/go -> /usr/lib64/go/1.11/bin/go
➜  ~ ll /usr/lib64/go/
total 0
drwxr-xr-x 1 root root 46 Aug 13 15:00 1.11
drwxr-xr-x 1 root root 46 Sep  1 07:47 1.12
➜  ~ 
```
Thanks

**Comment by dotboris** [comment]
Sadly, `alt scan` only supports certain conversions of having multiple versions of a command on a system.

Good news is that you can still use `alt` with go. You'll need to use `alt def` instead of `alt scan`.

```sh
alt def go 1.11 /usr/lib64/go/1.11/bin/go
alt def go 1.12 /usr/lib64/go/1.12/bin/go
```

This will tell alt about those two versions.

If you install a new version of go, you'll need to tell alt about it by running: 
(replacing `{version}` with the version referencing)

```sh
alt def go {version} path/to/bin/go
```

**Comment by vzool** [comment]
Thanks
